# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: plecompt <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/11/11 20:18:54 by plecompt          #+#    #+#              #
#    Updated: 2014/11/12 15:09:21 by plecompt         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

    NAME = libft.a

    CC = gcc

    SRC =	ft_putstr.c \
			ft_atoi.c \
			ft_bzero.c \
			ft_isalnum.c \
			ft_isalpha.c \
			ft_isascii.c \
			ft_isdigit.c \
			ft_isprint.c \
			ft_memccpy.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_memcpy.c \
			ft_memmove.c \
			ft_memset.c \
			ft_strcat.c \
			ft_strchr.c \
			ft_strcmp.c \
			ft_strcpy.c \
			ft_strdup.c \
			ft_strlcat.c \
			ft_strlen.c \
			ft_strncat.c \
			ft_strncmp.c \
			ft_strncpy.c \
			ft_strnstr.c \
			ft_strrchr.c \
			ft_strstr.c \
			ft_tolower.c \
			ft_toupper.c \
			ft_putchar.c \
			ft_putnbr.c \
			ft_memalloc.c \
			ft_memdel.c \
			ft_strnew.c \
			ft_strdel.c \
			ft_strclr.c \
			ft_striter.c \
			ft_striteri.c \
			ft_strmap.c \
			ft_strmapi.c \
			ft_strequ.c \
			ft_strnequ.c \
			ft_strsub.c \
			ft_strjoin.c \
			ft_strtrim.c \
			ft_strsplit.c \
			ft_itoa.c \
			ft_putendl.c \
			ft_putchar_fd.c \
			ft_putstr_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c \
			ft_putstr_color.c \
			ft_putchar_color.c \
			ft_putnbr_color.c \
			get_next_line.c \

OBJ  = $(SRC:.c=.o) 

CC_FLAGS = -c -Wall -Wextra -Werror -g3

all: $(NAME)

$(NAME):

	@echo "\n"
	@echo "                       	      ~   .ueu.u11111111Wu."
	@echo "                                .111111111111111111Wu"
	@echo "                                :111111111111111111111Wu."
	@echo "                                1111111111111111111111111W."
	@echo "                                 11111111111111111111*11111T"
	@echo "                                 11111111111111111*@~ ~@111~"
	@echo "                                :11111111111111111~    :11^"
	@echo "                                 *11111111111111*~~~:   1+"
	@echo "                                  11111@%@1111^ :~.:uu~~1"
	@echo "                                  11111! ~@11~    (UU@!i*"
	@echo "                                 11111@! ::!~     @@T*!11"
	@echo "                                 **111!~!**           !~^~"
	@echo "                                   11TH  !:            1"
	@echo "                                   1*?~   ~         ~+Xi"
	@echo "                                  !1~~    !         :W^*"
	@echo "                                  1?      !W.      @1~v"
	@echo "                                 !1   :   ~11i.    !T"
	@echo "                                 W!   ~    1^T^*ou:1!"
	@echo "                             . :*^         ~ ~   **^^~+:.."
	@echo "                         ..Ue@^*             ~           \\"
	@echo "                      .W11RMMM                            @."
	@echo "                     :1MMMMMM8                            ~!"
	@echo "                    .1MMMMMMMR!                           ~!"
	@echo "                    W1MMMMMMMM8                           !!"
	@echo "                   :1RMMMMMMM@RX                  .      ~~1"
	@echo "                   WRMM8MMMMMM11:                 !       ~T"
	@echo "                   1MM11MM1MMM111:               !~       ~W"
	@echo "                  :11MM11M1MBMMR1@:              !        :1"
	@echo "                  UM11@8B11M@MMMMM@:             !        !1"
	@echo "                  1MMMMMR11M1MMMMMM1!           :!        !*"
	@echo "                 !1MMMMMMM1M1MMMMMMM1:          !!       ~1~"
	@echo "                 *11@@@1888M1MMMMMMMM1:         !!       !1"
	@echo "                  11MMMM@M1MRMMMMMMMM1W!        X~      :HT"
	@echo "                  *8MM@RRR1MMMMMMMMMMRRW        M     : ~1~"
	@echo "                  !1MMMMMM1MM8MMMMMMM8@1       .1eiou:  X1u"
	@echo "                  !!MMMM@R1MM1MMMMMMMMMMX   .uW11111111W111Wu um@@@@*Wu"
	@echo "                  *!MMMMB1*8MRMMMMMMMMMM1!:H118811111111111111@~~~~~~?*W."
	@echo "                   !11@^* ~1MMMMMMMMMMM111RM11BB1111111111111~~~~~~~~~~@W"
	@echo "                    ^(!    MMMMMMMMMMMM1RRM1RM1R11111111111@~~~~~~~~~~~!1"
	@echo "                     -!    !MMMMMMMMMM11MMM181BMR111111111*~~~~~~~~~~~~!1"
	@echo "                      *    !1MM@MMMMMM11@M1118111R8111111*~~~~~~~~~~~~!!1"
	@echo "                      !:   ~RMMMMMMMMMM1MMM11B88188R11111!~~~~~~~~~~~~~!1"
	@echo "                      (:    !MMM1MMMR1M18M11@^@1B1B1B111?~ ~~~~~~~~~~~~W!"
	@echo "                      !!     ?MMMMMMMR1118R1~  *@11111@^ ~ ~~~~~~~~~~~:1!"
	@echo "                      *W      MMMMMMMMR1811?     *@111~    ~::~~~~~~~~B*"
	@echo "                       1:     *MM1MMMMMM111~      XR1~       ~~~~~~~~!1!"
	@echo "                       ^W      !M18M88818MT       18!           ~~~~:1*"
	@echo "                        TX      ?M118M88R1~      XMM            ~~~~X1~"
	@echo "                        *1:     ~M1M@8MM1M      :11~            :~:!8T"
	@echo "                         *@      !18MR1M1~      11!              :!!1"
	@echo "                          !X      M1MMM1M      U8?             .!~~1~"
	@echo "                         .1BX     !1R18M!     !1?             :~ :WT"
	@echo "                  ........***!     RMMR1     :1?            :~   !1"
	@echo "             .ue1*@^^^*       :    ~@8M?     W?           :~    ~WT"
	@echo "         ue@*^^               ~:    ~*1!    !?          :~    ~~:1!"
	@echo "      .*^^*                     :     T     !~        :!        H*"
	@echo "    .~                          ~:    ~     ~!       !*        :1*"
	@echo "   !                             ~   ~~      !     :~         :1^"
	@echo "  (           ..:--~***~--:.     :   !      ::   .X..        x1^"
	@echo "  !                         *~--::X !     ~: !  !^   ~:   .uW1^"
	@echo "  !                                ~     -    ~!      *!W***^*"
	@echo " ~!                               ~ !  +.     !*        ^^^***^@W."
	@echo "  *X                             ! /*~ !~:   !~                ~*1:"
	@echo "   *\                            !~  ~  -.!!*                    *@e."
	@echo "     -eu.                       /     *-..!:                   -:.~1"
	@echo "      .^*11Woouu..............:~        X1*****@We=====mm*****Wu:!!1"

	@$(CC) $(CC_FLAGS) $(SRC)
	@ar rc $(NAME) $(OBJ)
	@echo "Library libft has been created"

.PHONY: clean fclean re

clean :
	@rm -f $(OBJ)

fclean: clean
	@rm -f $(NAME)
	@echo "Library and objects has been cleaned for libft"

re: fclean all
